### PR TITLE
Website with drawing

### PR DESCRIPTION
**Pull request by ferib**
Hacktoberfest is back and I decided now is a good time to move some changes from my old school project (Cordova-inpaint) to the InpaintingSite repo.

- Update website UI.
- Add JS drawing for both Mobile and Desktop mouse events.
- Add gallery to show image history.
- Painting with a Dot (can "push" it around instead of dragging, really handy for mobile).
- Updated NancyFx bootstrap to use ``/img/`` and ``/css/`` directory's.

### CODE REVIEW

**Comment by ferib** [comment]
Alright,

I have figured out a way to keep the images (background img + canvas) ontop of each other without messing up the JS MaskHandler *(bug fixed drawing offset)*.
Everything should look good now.

**Comment by zavolokas** [comment]
> Alright,
> 
> I have figured out a way to keep the images (background img + canvas) ontop of each other without messing up the JS MaskHandler _(bug fixed drawing offset)_.
> Everything should look good now.

@ferib there are some issues related to merge 

image

**Comment by ferib** [comment]
@zavolokas I have resolved the conflicts 🎉

**Review by zavolokas — APPROVED** [review]
Great job @ferib! 🙌

**Pull request merged**
